# Generated by Django 5.0.6 on 2024-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
        ('events', '0002_photo_event_template_event_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.event'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('guest', 'Guest')], default='guest', max_length=100),
        ),
    ]
