# Generated by Django 5.0.6 on 2024-07-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_rename_logs_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
