# Generated by Django 5.0.6 on 2024-07-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('json_data', models.JSONField()),
            ],
        ),
    ]
